- name: Install OpenJDK 1.8
  dnf:
    name: java-1.8.0-openjdk.x86_64
    state: latest
- name: Install OpenJDK 11
  dnf:
    name: java-11-openjdk.x86_64
    state: latest
- name: Install OpenJDK Latest
  dnf:
    name: java-latest-openjdk.x86_64
    state: latest